# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.CharField(max_length=128)),
                ('addedon', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=256)),
                ('nid', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TripCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('trip_cost', models.CharField(max_length=256)),
                ('cost_oil', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TripList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('trip_description', models.CharField(max_length=256)),
                ('trip_earn', models.CharField(max_length=256)),
                ('car_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.CarList')),
            ],
        ),
        migrations.CreateModel(
            name='TripNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('trip_number', models.CharField(max_length=256)),
                ('car_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.CarList')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DriverName')),
            ],
        ),
        migrations.AddField(
            model_name='triplist',
            name='trip_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.TripNumber'),
        ),
        migrations.AddField(
            model_name='tripcost',
            name='trip_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.TripNumber'),
        ),
    ]
