# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplist',
            name='car_no',
        ),
    ]
