# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_tripcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcost',
            name='trip_number',
        ),
        migrations.DeleteModel(
            name='TripCost',
        ),
    ]
