# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20171230_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('dieasel_liter', models.CharField(max_length=256)),
                ('dieasel_amount', models.CharField(max_length=256)),
                ('feri_bridge', models.CharField(max_length=256)),
                ('police_labour', models.CharField(max_length=256)),
                ('chada', models.CharField(max_length=256)),
                ('tada', models.CharField(max_length=256)),
                ('car_parts', models.CharField(max_length=256)),
                ('others', models.CharField(max_length=256)),
                ('trip_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.TripNumber')),
            ],
        ),
    ]
