# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_tripcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripcost',
            old_name='tada',
            new_name='khoraki',
        ),
    ]
