# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0013_auto_20180102_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('car_no', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DriverName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=256)),
                ('nid', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TripCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('trip_number', models.CharField(max_length=256)),
                ('dieasel_liter', models.CharField(max_length=256)),
                ('dieasel_amount', models.CharField(max_length=256)),
                ('feri_bridge', models.CharField(max_length=256)),
                ('police_labour', models.CharField(max_length=256)),
                ('chada', models.CharField(max_length=256)),
                ('khoraki', models.CharField(max_length=256)),
                ('car_parts', models.CharField(max_length=256)),
                ('others', models.CharField(max_length=256)),
                ('car_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.CarList')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DriverName')),
            ],
        ),
        migrations.CreateModel(
            name='TripList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedon', models.DateTimeField(auto_now=True)),
                ('trip_description', models.CharField(max_length=256)),
                ('trip_earn', models.CharField(max_length=256)),
                ('trip_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.TripCost')),
            ],
        ),
    ]
