# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_carlist_drivername_tripcost_triplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='car_no',
            new_name='car_number',
        ),
        migrations.RenameField(
            model_name='drivername',
            old_name='driver_name',
            new_name='name',
        ),
    ]
