# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20180102_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcost',
            name='car_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.CarList'),
        ),
    ]
