# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20180102_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlist',
            options={'ordering': ['-addedon']},
        ),
        migrations.AlterModelOptions(
            name='tripcost',
            options={'ordering': ['-addedon']},
        ),
    ]
