# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20180106_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcost',
            name='trip_earn_money',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
